<a href="https://colab.research.google.com/github/MarinaSamusenkova/DataAnalisysInnopolis/blob/main/%D0%A1%D0%B0%D0%BC%D1%83%D1%81%D0%B5%D0%BD%D0%BA%D0%BE%D0%B2%D0%B0_%D0%9C_%D0%A1__%D0%94%D0%97%E2%84%962_%D0%B1%D0%BB%D0%BE%D0%BA2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('coffee.csv')
data

,Location.Country,Location.Region,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Owner,Data.Type.Species,Data.Type.Variety,Data.Type.Processing method,...,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total,Data.Color
0,United States,kona,0,0,0,2010,kona pacific farmers cooperative,Arabica,NaN,NaN,...,8.42,8.08,7.75,7.67,7.83,10.00,10.00,0.00,86.25,Unknown
1,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,7.92,7.75,8.33,8.00,10.00,10.00,0.08,86.17,Unknown
2,Brazil,sul de minas - carmo de minas,12,12,12,2010,jacques pereira carneiro,Arabica,Yellow Bourbon,NaN,...,7.92,8.00,7.75,7.92,8.00,10.00,10.00,0.01,86.17,Unknown
3,Ethiopia,sidamo,0,0,0,2010,ethiopia commodity exchange,Arabica,NaN,NaN,...,8.00,7.83,8.00,7.92,7.83,10.00,10.00,0.00,85.08,Unknown
4,Ethiopia,sidamo,0,0,0,2010,ethiopia commodity exchange,Arabica,NaN,NaN,...,7.83,7.58,8.00,7.83,7.50,10.00,10.00,0.10,83.83,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,Guatemala,san marcos,1700,1700,1700,2017,juan luis alvarado romero,Arabica,Bourbon,Washed / Wet,...,7.67,7.42,7.42,7.67,7.67,8.67,8.67,0.10,79.08,Green
985,Honduras,comayagua,1400,1400,1400,2017,bismarck castro,Arabica,Caturra,NaN,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.12,0.00,Green
986,India,chikmagalur karnataka indua,3170,3170,3170,2017,nishant gurjer,Robusta,NaN,Washed / Wet,...,7.75,7.92,8.00,7.92,7.92,10.00,8.00,0.00,83.50,Unknown
987,India,chikmagalur karnataka india,3140,3140,3140,2017,nishant gurjer,Robusta,NaN,Washed / Wet,...,7.75,7.83,7.67,7.92,7.83,10.00,7.92,0.10,82.50,Bluish-Green
988,Honduras,western region,1200,1200,1200,2018,mdh,Arabica,Catimor,Washed / Wet,...,7.42,7.08,7.42,7.50,7.33,10.00,10.00,0.11,81.58,Blue-Green

Датасет содержит 989 строк и 23 столбца. Он описывает всевозможные показатели, характеристики, такие как кислотность, плотность, аромат и др. сортов кофе арабики и робусты из разных стран, также учитывается высота над уровнем моря места произрастания, сорт, год урожая, общий объем урожая по количеству мешков и весу мешка, способ обработки зерна.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 989 entries, 0 to 988
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Location.Country                989 non-null    object
 1   Location.Region                 953 non-null    object
 2   Location.Altitude.Min           989 non-null    int64
 3   Location.Altitude.Max           989 non-null    int64
 4   Location.Altitude.Average       989 non-null    int64
 5   Year                            989 non-null    int64
 6   Data.Owner                      984 non-null    object
 7   Data.Type.Species               989 non-null    object
 8   Data.Type.Variety               864 non-null    object
 9   Data.Type.Processing method     927 non-null    object
 10  Data.Production.Number of bags  989 non-null    int64
 11  Data.Production.Bag weight      989 non-null    float64
 12  Data.Scores.Aroma               989 non-null    float64
 13  Data.Scores.Flavor              989 non-null    float64
 14  Data.Scores.Aftertaste          989 non-null    float64
 15  Data.Scores.Acidity             989 non-null    float64
 16  Data.Scores.Body                989 non-null    float64
 17  Data.Scores.Balance             989 non-null    float64
 18  Data.Scores.Uniformity          989 non-null    float64
 19  Data.Scores.Sweetness           989 non-null    float64
 20  Data.Scores.Moisture            989 non-null    float64
 21  Data.Scores.Total               989 non-null    float64
 22  Data.Color                      989 non-null    object
dtypes: float64(11), int64(5), object(7)
memory usage: 177.8+ KB

Численные значения, как целые, так и с дробной частью содержатся в большинстве столбцов, поскольку оценка по характеристикам кофе дана в основном в числовом виде, возможно балльном, кроме характеристики "Цвет/Color". В строчном /object/ типе представлены данные по 7 столбцам: Страна, Регион, Владелец, Сорт, Подвид, Способ обработки, Цвет. Нулевые значения есть в столбцах Регион /36/, Владелец /5/, Подвид /125/, Способ обработки /62/.

In [ ]:
data.describe()

,Location.Altitude.Min,Location.Altitude.Max,Location.Altitude.Average,Year,Data.Production.Number of bags,Data.Production.Bag weight,Data.Scores.Aroma,Data.Scores.Flavor,Data.Scores.Aftertaste,Data.Scores.Acidity,Data.Scores.Body,Data.Scores.Balance,Data.Scores.Uniformity,Data.Scores.Sweetness,Data.Scores.Moisture,Data.Scores.Total
count,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000,989.000000
mean,1640.076845,1675.929221,1657.998989,2013.549039,151.761375,210.491937,7.572831,7.515410,7.387472,7.539697,7.506309,7.500344,9.823893,9.830313,0.093903,81.972133
std,9192.519762,9191.957731,9192.058989,1.658883,125.665490,1666.707294,0.396796,0.420677,0.425284,0.399370,0.391481,0.425055,0.593888,0.691316,0.044666,3.859562
min,0.000000,0.000000,0.000000,2010.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,905.000000,950.000000,950.000000,2012.000000,15.000000,1.000000,7.420000,7.330000,7.250000,7.330000,7.330000,7.330000,10.000000,10.000000,0.100000,81.080000
50%,1300.000000,1310.000000,1300.000000,2013.000000,170.000000,60.000000,7.580000,7.500000,7.420000,7.580000,7.500000,7.500000,10.000000,10.000000,0.110000,82.500000
75%,1550.000000,1600.000000,1600.000000,2015.000000,275.000000,69.000000,7.750000,7.750000,7.580000,7.750000,7.670000,7.750000,10.000000,10.000000,0.120000,83.580000
max,190164.000000,190164.000000,190164.000000,2018.000000,600.000000,19200.000000,8.750000,8.830000,8.670000,8.750000,8.500000,8.580000,10.000000,10.000000,0.280000,90.580000

Сомнение вызывает максимальное значение высоты над уровнем моря Altitude /190164/, поскольку не понятно, в каких величинах приведены значения, самая высоткая точка в мире составляет 8849 м над уровнем моря, похоже на выброс. Также странно, что все три колонки высоты Altitude, минимальная-максимальная-средняя, содержат это максимальное значение, и в целом по статистическим данным практически повторяют друг друга.
Также странное значение имеет максимальное значение веса мешка /19200/, также не понятно, в каких величинах даны значения, если в кг, то такое значение похоже на выброс.
При этом минимальное количество мешков - /1/, а минимальный вес мешка - /0/, что также наводит на мысли о некорректности данных, либо для таблицы установлено, что количество мешков не может быть нулевым.
Все характеристики сортов содержат значения min /0/, что говорит о том, что некоторые сорта не были оценены, и чтобы не оставлять пустые значения, они были заполнены числом /0/.